export const CLASS_NAME = {
  app: 'app',
  appHeader: 'app__header',
  appTitle: 'app__title',
  menuButton: 'menu-btn',
  modalBackdrop: 'modal__backdrop',
  modalContainer: 'modal-container',
  modalSlot: 'modal-slot',
  modalCloseButton: 'close-btn',
  tabStealer: 'tab-stealer',
  form: 'add-form',
  controlArea: 'control-wrap',
  control: 'control',
  controlLabel: 'control__label',
  controlInput: 'control__input',
  contentList: 'app__contents',
  addButton: 'add-btn',
  contentItem: 'content',
  contentFigure: 'content__figure',
  contentText: 'content__description',
  contentTitle: 'content__title',
  itemRemoveButton: 'rm-btn',
  draggable: 'draggable',
  dragging: 'dragging',
  dragover: 'dragover',
  scroll: 'scroll',
  hidden: 'hidden',
} as const;
